import type { Metadata } from "next";
import { site } from "./site";

/** Default OG image route generated by `src/app/opengraph-image.tsx`. */
const defaultOg = "/opengraph-image";

export function createMetadata(overrides: {
  title: string;
  description?: string;
  path?: string;
}): Metadata {
  const description = overrides.description ?? site.description;
  const url = `${site.url}${overrides.path ?? ""}`;

  return {
    title: overrides.title,
    description,
    openGraph: {
      title: `${overrides.title} | ${site.shortName}`,
      description,
      url,
      siteName: site.name,
      locale: "en_US",
      type: "website",
      images: [
        {
          url: defaultOg,
          width: 1200,
          height: 630,
          alt: `${site.name} — ${site.slogan}`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `${overrides.title} | ${site.shortName}`,
      description,
      images: [defaultOg],
    },
    alternates: {
      canonical: url,
    },
  };
}
